### ISSUE TITLE
Sidebar for query history

### ISSUE THREAD

**Issue by cjblink1** [CTVisualizer/front-end#3]
As a sidebar, I can view my recent queries in the sidebar so that I can more easily populate the query input field.

**Comment by shahdk** [comment]
It would also be nice to have the results pre-populated. That is, if I select the query from the recent queries, it would be nice to not have to run the query again. I can run it if I want an updated result, otherwise just load the old result back

**Comment by TravisJRyan** [comment]
Implemented in 1.0.18 @shahdk
